### ISSUE TITLE
The upgrade bridge action is failing

### ISSUE THREAD

**Issue by adinhodovic** [pulumiverse/pulumi-cockroach#46]
Hey @ringods,

Seems like this action is continuously failing https://github.com/pulumiverse/pulumi-cockroach/actions/runs/11433713513/job/31806125167 due to GH authentication.

We need this resource https://registry.terraform.io/providers/cockroachdb/cockroach/latest/docs/resources/metric_export_prometheus_config, which was added in May and I expected it to exist in the Pulumi provider.

Thanks!

**Comment by ringods** [comment]
I'm working on getting https://github.com/pulumi/ci-mgmt/ to work for thirdparty providers (like the Pulumiverse ones). The process around kicking of `upgrade-provider` tool to upgrade the bridge or upstream provider is in it's last phases. Once that is ready, I can generate the correct workflows from the templates in `ci-mgmt`.

**Comment by adinhodovic** [comment]
> I'm working on getting https://github.com/pulumi/ci-mgmt/ to work for thirdparty providers (like the Pulumiverse ones). The process around kicking of `upgrade-provider` tool to upgrade the bridge or upstream provider is in it's last phases. Once that is ready, I can generate the correct workflows from the templates in `ci-mgmt`.

Awesome, thanks!

**Comment by adinhodovic** [comment]
> I'm working on getting https://github.com/pulumi/ci-mgmt/ to work for thirdparty providers (like the Pulumiverse ones). The process around kicking of `upgrade-provider` tool to upgrade the bridge or upstream provider is in it's last phases. Once that is ready, I can generate the correct workflows from the templates in `ci-mgmt`.

Will the provider be upgraded to the latest one automatically after that (1.6.0 -> 1.9.0)? Thanks!

**Comment by ringods** [comment]
@adinhodovic upgrade to the latest bridge, together with upgrade to upstream TF provider v1.9.0, worked in #54. Releasing that one as v0.7.0 right now.

**Comment by adinhodovic** [comment]
> @adinhodovic upgrade to the latest bridge, together with upgrade to upstream TF provider v1.9.0, worked in #54. Releasing that one as v0.7.0 right now.

Thanks!! :rocket:
